### ISSUE TITLE
Cant seem to get it working in laravel

### ISSUE THREAD

**Issue by hugocabral** [Metrakit/VisualCaptcha-Laravel#3]
I followed the steps you wrote on readme, added the same HTML you added in the captcha.blade.php in my form but nothing is shown.
I even added in my main.layout the script from AngularJS. 
Am i missing something?

**Comment by BrunoBernardino** [comment]
Can you show us some code for your repo? Maybe any errors logged?

**Comment by Metrakit** [comment]
Hi, sorry i was unaivable for a time because Im doing a trip now. Yes we need your code for can help you. The example works for me, I have tried again just now.
